//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.3

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "beat_saber_versions")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(unique)]
    pub ver: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::mod_beat_saber_versions::Entity")]
    ModBeatSaberVersions,
    #[sea_orm(has_many = "super::version_beat_saber_versions::Entity")]
    VersionBeatSaberVersions,
}

impl Related<super::mod_beat_saber_versions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ModBeatSaberVersions.def()
    }
}

impl Related<super::version_beat_saber_versions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::VersionBeatSaberVersions.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
