//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.3

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "beat_saber_versions")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(column_type = "Text", unique)]
    pub ver: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl Related<super::versions::Entity> for Entity {
    fn to() -> RelationDef {
        super::version_beat_saber_versions::Relation::Versions.def()
    }
    fn via() -> Option<RelationDef> {
        Some(
            super::version_beat_saber_versions::Relation::BeatSaberVersions
                .def()
                .rev(),
        )
    }
}

impl ActiveModelBehavior for ActiveModel {}
