//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.3

pub mod prelude;

pub mod beat_saber_versions;
pub mod categories;
pub mod mod_beat_saber_versions;
pub mod mod_stats;
pub mod mod_versions;
pub mod mods;
pub mod user_mods;
pub mod users;
pub mod version_beat_saber_versions;
pub mod version_conflicts;
pub mod version_dependents;
pub mod version_stats;
pub mod versions;
