//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.3

pub mod prelude;

pub mod beat_saber_versions;
pub mod categories;
pub mod mod_stats;
pub mod mod_versions;
pub mod mods;
pub mod users;
pub mod users_mods;
pub mod version_beat_saber_versions;
pub mod version_stats;
pub mod versions;
pub mod versions_conflicts;
pub mod versions_dependents;
