//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.3

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "mods")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(unique)]
    pub slug: String,
    pub name: String,
    pub description: Option<String>,
    pub icon: Option<String>,
    pub cover: Option<String>,
    pub website: Option<String>,
    pub author: Uuid,
    pub category: Uuid,
    #[sea_orm(unique)]
    pub stats: Uuid,
    pub created_at: DateTime,
    pub updated_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::categories::Entity",
        from = "Column::Category",
        to = "super::categories::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Categories,
    #[sea_orm(has_many = "super::mod_beat_saber_versions::Entity")]
    ModBeatSaberVersions,
    #[sea_orm(
        belongs_to = "super::mod_stats::Entity",
        from = "Column::Stats",
        to = "super::mod_stats::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    ModStats,
    #[sea_orm(has_many = "super::mod_versions::Entity")]
    ModVersions,
    #[sea_orm(has_many = "super::user_mods::Entity")]
    UserMods,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::Author",
        to = "super::users::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Users,
    #[sea_orm(has_many = "super::versions::Entity")]
    Versions,
}

impl Related<super::categories::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Categories.def()
    }
}

impl Related<super::mod_beat_saber_versions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ModBeatSaberVersions.def()
    }
}

impl Related<super::mod_stats::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ModStats.def()
    }
}

impl Related<super::mod_versions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ModVersions.def()
    }
}

impl Related<super::user_mods::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserMods.def()
    }
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Users.def()
    }
}

impl Related<super::versions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Versions.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
